language: php

sudo: false

env:
  - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 7.1
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true
    - php: 7.3
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true
    - php: 7.4
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true
    - php: master
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
  allow_failures:
    - php: master
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
  - composer phpunit

after_script:
 - if [ "$COLLECT_COVERAGE" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi
 - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs; fi
